// <auto-generated />
namespace QuanLyKho.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addKhachhang_NhanVien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addKhachhang_NhanVien));
        
        string IMigrationMetadata.Id
        {
            get { return "201810090331498_addKhachhang_NhanVien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
